### ISSUE TITLE
It's showing errors alots of

### ISSUE THREAD

**Issue by SanjeevYadav34** [DARK-02/InstaFollower#3]

**Comment by SanjeevYadav34** [comment]
Too much errors

**Comment by SanjeevYadav34** [comment]
» <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131;font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,"Apple Color Emoji","Segoe UI Emoji",Segoe UI Symbol,"Noto Color Emoji"}button{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,"Apple Color Emoji","Segoe UI Emoji",Segoe UI Symbol,"Noto Color Emoji"}@mixin dark-mode{background-color: #222; color: #d9d9d9; a {color: #fff; &:hover {text-decoration: underline; color: #ee730a;}} .lds-ring div {border-color: #999 transparent transparent;} .font-red {color: #b20f03;} .big-button,.pow-button {background-color: #4693ff; color: #1d1d1d;} #challenge-success-text {background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4);}}@mixin light-mode{background-color: transparent; color: #313131; a {color: #0051c3; &:hover {text-decoration: underline; color: #ee730a;}} .lds-ring div {border-color: #595959 transparent transparent;} .font-red {color: #fc574a;} .big-button,.pow-button {border-color: #003681; background-color: #003681; color: #fff;} #challenge-success-text {background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=);}}@media (prefers-color-scheme: dark){body{@include dark-mode;}}body{display:flex;flex-direction:column;min-height:100vh;&.no-js{.loading-spinner{visibility:hidden}.challenge-running{display:none}}&.dark{@include dark-mode;}&.light{@include light-mode;}}a{transition:color .15s ease;background-color:transparent;text-decoration:none;color:#0051c3;&:hover{text-decoration:underline;color:#ee730a}}.main-content{margin:8rem auto;width:100%;max-width:60rem}.heading-favicon{margin-right:.5rem;width:2rem;height:2rem}@media (width <= 720px){.main-content{margin-top:4rem}.heading-favicon{width:1.5rem;height:1.5rem}}.main-content,.footer{padding-right:1.5rem;padding-left:1.5rem}.main-wrapper{display:flex;flex:1;flex-direction:column;align-items:center}.font-red{color:#b20f03}.spacer{margin:2rem 0}.h1{line-height:3.75rem;font-size:2.5rem;font-weight:500}.h2{line-height:2.25rem;font-size:1.5rem;font-weight:500}.core-msg{line-height:2.25rem;font-size:1.5rem;font-weight:400}.body-text{line-height:1.25rem;font-size:1rem;font-weight:400}@media (width <= 720px){.h1{line-height:1.75rem;font-size:1.5rem}.h2{line-height:1.5rem;font-size:1.25rem}.core-msg{line-height:1.5rem;font-size:1rem}}#challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+);background-repeat:no-repeat;background-size:contain;padding-left:34px}#challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjMzEzMTMxIiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=);background-repeat:no-repeat;background-size:contain;padding-left:42px}.text-center{text-align:center}.big-button{transition-duration:.2s;transition-property:background-color,border-color,color;transition-timing-function:ease;border:.063rem solid #0051c3;border-radius:.313rem;padding:.375rem 1rem;line-height:1.313rem;font-size:.875rem;&:hover{cursor:pointer}}.captcha-prompt:not(.hidden){display:flex}@media (width <= 720px){.captcha-prompt:not(.hidden){flex-wrap:wrap;justify-content:center}}.pow-button{margin:2rem 0;background-color:#0051c3;color:#fff;&:hover{border-color:#003681;background-color:#003681;color:#fff}}.footer{margin:0 auto;width:100%;max-width:60rem;line-height:1.125rem;font-size:.75rem}.footer-inner{border-top:1px solid #d9d9d9;padding-top:1rem;padding-bottom:1rem}.clearfix{&:after{display:table;clear:both;content:""}.column{float:left;padding-right:1.5rem;width:50%}}.diagnostic-wrapper{margin-bottom:.5rem}.footer .ray-id{text-align:center;code{font-family:monaco,courier,monospace}}.core-msg,.zone-name-title{overflow-wrap:break-word}@media (width <= 720px){.diagnostic-wrapper{display:flex;flex-wrap:wrap;justify-content:center}.clearfix:after{display:initial;clear:none;text-align:center;content:none}.column{padding-bottom:2rem}.clearfix .column{float:none;padding:0;width:auto;word-break:keep-all}.zone-name-title{margin-bottom:1rem}}.loading-spinner{height:76.391px}.lds-ring{display:inline-block;position:relative;width:1.875rem;height:1.875rem;div{box-sizing:border-box;display:block;position:absolute;border:.3rem solid #595959;border-radius:50%;border-color:#313131 transparent transparent;width:1.875rem;height:1.875rem;animation:lds-ring 1.2s cubic-bezier(.5,0,.5,1) infinite;&:nth-child(1){animation-delay:-.45s}&:nth-child(2){animation-delay:-.3s}&:nth-child(3){animation-delay:-.15s}}}@keyframes lds-ring{0%{transform:rotate(0)}to{transform:rotate(360deg)}}@media screen and (-ms-high-contrast: active),screen and (-ms-high-contrast: none){body,.main-wrapper{display:block}}</style><meta http-equiv="refresh" content="375"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div id="challenge-error-title"><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: '3',cZone: "qlizz.com",cType: 'managed',cNounce: '12412',cRay: '850dd80eda274db0',cHash: '717d25b51fbf63e',cUPMDTk: "\/?__cf_chl_tk=fJvNj6gd0lAy1InlMqhy49ZV1Xztz9N92uh0mWVxpP4-1707164321-0-gaNycGzNENA",cFPWv: 'g',cTTimeMs: '1000',cMTimeMs: '375000',cTplV: 5,cTplB: 'cf',cK: "visitor-time",fa: "\/?__cf_chl_f_tk=fJvNj6gd0lAy1InlMqhy49ZV1Xztz9N92uh0mWVxpP4-1707164321-0-gaNycGzNENA",md: "SnfulzWNgJZRUe0g.kfncm8kRAZwQDWiMDLbjLHltuo-1707164321-1-ATWEbZk7MqtcjOQI5fe0IcUleO4oyZlvFyNlVNtYF1Z0Q4NyStqelY7fMWnw-_OZ_4dvLUm3AiTACWmtYOu-D7SZU0UY578PjMMh3SHFolDq49_0In6VWBnIHxSFdXjwAV_G9xMcT6wySGDy8JjRstZmuC6d4YrJBKU2yKt269FJoQnTfJlTDLU9TiWiDk2fj6lBm7EsuA39QHXhcWSRkW_gelmQiIZegatAGOYhp6NS-gNJs2xd5nBFW3DUFEGYFIdWpDgsBbVgq0_rsL1U-ocVpUO1d1DwiJTYLX5Aax3msv_9Ph4FqnJ4ht5BqELrR8gGDOD3kbgOOY0RaeBZ8PIGBBkw-wpaGZkia8SJ8nlM1H8TGXDGIJJ5yqJRK0K2sO_CWe7mHbykhoOPP98ksMK98z_BV21QNtgTzhn_zrLDN-jqUXzX63NqqcNfH70smoNqHtMAAWqwm7Xp_xktjdA2Jr2NvxyO4mImezdZd0u-jLEww68ImomruHaw0PhMGX4x5GiuptkMnvM7q7AdTRNwFHCEkzoutqXbgp-R-6PdZVWFIlkbZh4WW2JlJg_88A07RQmWQVSuZud0E3qTd8NPNVD8btfMSS-R3u3vJxcp5W6ndZTOFEkQrIUVFMPjh7F36WeMVSdVibU4FHQ8eTgszwiNfbyhJcxJEFMSrRaHiXDwF7qrYf6iJgG09zJnWxMRv8nCXeDneEdonoemuzg96CHhlSIyehhfo8gDkQpbZ2YzcvGxa8jta19V80dzZNhA485gOKQID_6A3JSUBv8GnDaXskOdNVXN32aE8U8QeDvRmduPgAfvTGTng1X4uId-9mM0x1GO9p2qtUwQozo18RpeR8i9Ekc9nU4Cd0qJ1g8O0h9gK2ryflnL532AWLa8NfqszqwQJ9_bDlNuAmurGsBgOUD1iQat_YCzBwwf4OjBkkmB4B91hp8avOqriAtcLS07aiCM90NUA_3hRpYF3x514YkGlx13aQPR5EobcrCMDauvO8vzGaga6b50IaQNfOS7TZLHxLrbgdaw0iH9pQ31Uhmx4mvoVQtggv3p9FUjmfpi78EJjJaBI99Pe3SF0P6L2-G0BER1gyKNJWyitz7MG83xcUntJHHVAjfv3JMiwn37HNxQ7UXgsQrgVeyhjCACE3BNMoWcLEclEdCC85LDi4dy7QfY08AEcgCY0xP6htf0KGqoy-cmd5b6JMnwFP47wtpX07rc_6rOUA79bYZkR_mlKTdlknN2it-q3p1y9JwiJ6mIcC2b2FxY9wlJEeKy1vX_jq8Mm7wa7Y4W7T7mlid8uW0lqWpbeMobNi14oTSqIaHLs0cYxOY_QsgqkFntIp1feg_iGmuqB4TJ76fKODnzMqZ-qraNEV8Z9BbFZIw7HKsmzr07D6MIF7Rpi7nypNiu0R_Cd62RqgHnefzT1JbJdhqBBEDW_Fmi9D1wa7taQ6oxFnJ4xJdRe7ZnLSkOSTCFn7C_BnirP7eDISQQU68tSicd6MpSiwB1Qzh8X4xnHh7TCSc-S5e_m5ncG6A5cQbOB8nr2YOURz-7VoPY61ynKtcnJSBOTOAjP3yrBslqflnpSXZv3jQs1UUDz5gxLcUglq7zfNuTn6ZLqycv7zugRZ8XbqwlBrs6yKl6S8WU11o11UfPRYt3sM8SQGSDRvVCxMbYvHgp7fwrD4J9J7UEg0kufERD_y_Kjet_y52e2_Po5qdfWZILeAeFNpi25oI-wACbE5ncPZs3gf0FqfNc-Tdvcu2gAMnXtqFZRq-IaBJdZ2yKzrieoiZ2hpmo5RzKk_SACDJezaHji2YCzbE9YuDgFA7jfssUaH1FjArUnwxWsQHyugl6eGCdU6yRWvPCrL21oIl-xvUNzo6Nx0PoH174TgJI1SO7NEOWuG2ldAvEwKnKV3HtREVskkeh7VG3-JGPFsy20oysPDk_slSAU3UmXF4OMQlpOrRi37uBiMMOrwNIbbQeLNi_xBfN75pIIisa2RIPe8-_XILGr2hjVOhl9GdeOhyKZQpIZPIFlq_bCKdbeB1CB8Nq_irjfA-8KGEFsVPiJfF_fKUBnLFioPMYtxgFGy6l-_yw0GQvE1NFZ3e_P6Y_QcvdQ-zh_cQr_bSifMwyA69IyXk-gkqmeys1Sve2ddtsfYVKgoqkVEB56cXoBN2zOJEUqYvmV886rOb6xBVbD6agioELw5Jq3PsPjUspmjzSU9A5OcHx9DmFo60saAbwLe3YcKXQDNcOThITdB3Jj--tdtGwCzlub-M1Y1-YXj7Bmv6o1joppAb1jxAl4jAx_u5_1eLK8VHI6h72nb05-r1V_44rOiPjvDuSu5xVLbxwWCu5oGT9HIFI8TYhelgDq6st9z9DREFvpG6X-lRYg9ZV3W0iTqHIBkFhp8pkM64n8GtRFGOP_VtPpDLxsLueHrc4kAWPMI7r1q-xpGETk6XTjVqmhTrxbc_tGHEMcUs12wvSYF9Zz-PbNO-HsSAaKiwQTKEKZ2DU9dJMv1Yq-LKxIhA-jWI55Eo_d8hOjGWEMVWKBEUTHAvM2aHGFd_B4xvExOzSKzRJ6a_fuxb6WhJHSH9EFDsWdNHHJxjyCxTw9nU2wao93XYzHCgsTgODE8toRnPcbuKcZt63rRWVL1NAYK3NHyOioHa2HoIqnrMz46Aw4wYLe2F8CG2mr-g9a6ht-FNnY5ytPHM8SC2iuP_KQTgdCaykFN43f8LUGCbQZ9x6X8Jvgvh2Yu8G877VaqyNH_5M6xmx_WTUUgYNHaCImER1TTWKmKLNYSJD7sHjocFOQuFkbx3s4jw2nK4qDCgKz2XFeAonJloHK0PhFyMl-E_DTzMEyX7hZSU1ImKSFyRvXIPcrBAWl8b_0BOjF3OGpW25aTrIKPL3VJtHdnEqJ1mSTvjheHcA2fDOEGREi3s_WpN219PJ3X4-J2F4LFFGxe9SvGBw1y8OXgmByT5vCuTvPykuPx_vTbhjDHwLTyW7nzuGiWfBcxxoYg6go90hhs4CTFSqr4oW0bgDg_UfrS-VnpBQupr8f_XP6ECInMLtpkyNs9zK82JcaXMznrngZTEVJmbV7H_6yDN1cSFvs371QCbh5RJOlsEcPh6cI9XDelt3w4_NBK-UNWFZ7u6YkuzSXpQlv2QVHLIEX-MbuI5KAED_0-pZ4sKEm2lg0EgAz8pldx9_RKcwSiNw789Ixy1YNOfrk_o9qPTNuyPHzYN87Cxr4FylhAtC7RGqoOzdFX1m4pS6mix7H4TSYtnqx6GR0f38mOI0juSCz-rySO42sunMKuO2miHeqK43rKk_CYSZndZk59SZ8SrrgL8BSJU4TQZ5gQwsMHqXRtvtnG63WP5w9U4B10oQXliuPzcF86FnLARHkI1ZvfXblsFVX8zkI73j64Ci1rwSs_WsNQHBYGzc86tCKlKDJwUnhVD7l4WGyMc5n2nhH126CjNlGJRaAHfL_9XCU1M7X8FoYQZjU1xMa46-SL8A5jtNkYz2M6pR7fphiVDWT2vVp7W55L2WlWoURDTDq-tIC7y_LIB8sgRj5_unh-GR8d36xxd97jPEaicXbsXiAIf2AGbWdcNfWjzSqivBKinV_B9kF-pVBIhMbrc__wepfeo--UHkF1VNpZROMPAP61dnuJySg_qdEIpYxmXVyo_kqR-Tibx8mUHucRJtsCxUu8WGMy6QU0WBuQnPE-Kr7pcz0FFqePJUOAnT2FahXmCkAspL45dX0DIgE2CqdqLLz5ZT61gvBr1aiHzwwRw6rYDDZqtKbcMY4NyEddVM2q89qsZpuOb2FzNB8Zry04Vn4ubmHesr_2J4f8O3_izhkDoqLi1ry9PnPb6kWzJlWUE3viyADmZBtUv9cJ8XeeK3bH73p9JoQGRlUcNGax0NgrYOrb4ZxCumU1mvV3gOUvk6fFvY-IBufZblxjMwm6ZVWpPJIAvwqt3HaFw3DysGUwreBpHjvwwPIObpeqzldvIiT4JN3wLt6ZRBPFPPW47Mk34I3eUNYMX_2yEOIt8Hp61pWZofHulhyfMhyqeSPeP6WJdBTTXymjNlcOyO8dM6CIIzCSO67UtYKT8MwexanCKC2PcdMf8q9uGDAVkZ_dc7eXYUd_5jQ4rvXw-k_u9XyfbH5wIgeUhlqqNr_6PjM9U7KWO1s59jmXQXd9FWElZbkbtAk9-GQMlJ7aNnwEWUQIeWKeFDa9V74u-R3prMF9w2Z0fv0mRVLARRmyUf7xVLARk",cRq: {ru: 'aHR0cHM6Ly9xbGl6ei5jb20v',ra: 'TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEwMS4wLjQ5NTEuNTQgU2FmYXJpLzUzNy4zNiBFZGcvMTAxLjAuMTIxMC4zOQ==',rm: 'R0VU',d: '423GOTFBXE80MQx9imSnpI5AX+2JK8WpQPHb+TwwpEsklG19/SYLQOcj9StTP4ljqbNJ5sBhzpsfGZVqDQttYR73PgFiqzmhcxvdwL+a6ufu5OM0IU7Ta9pa7KdVGJ3NXBYWaE3iE5TKhpuLQ6T2r7Gn9PTRgfo0nvoQWO1smkM5viUHnXA0TEKAGCzSdWfyT7UdJNIFxzDcl1JKhaU25lx22BDNOtkzdN4lcLFWX+pTX3/+lkIL5/WAZtk7aWpHxKkZiokgy1pDTcAV4+nGgc+iY/6o4pHZ97ykx6QXfEh01Abp0X3nGLTqEGRVGLFBXSyiHKYecdiHDYMttVBEhWyEX30nzoKIU0bRwfbHch3KaBeGlKTUr5pF/cGIoeiItK3VIrYwsxUPDBgZbmw4RWTStC5qKG4t3WIU4XAULdqBQ3hCIehe/iPmz4bp8AdmVpn0PhQ+oKTwaMTViCUse5CjBs4p89s7swA2YUkjAyRADocvwblvSdo6B3EBsy+MUApVAXJ+njoovK/DYI4hcpAPg9OBxsAiJvjPRZYHXCc2jZT+g9wlG00ETgJyICD4evIgY5NAFYXtGLhjQwDrRQ==',t: 'MTcwNzE2NDMyMS4xMDAwMDA=',cT: Math.floor(Date.now() / 1000),m: 'iz8IGUC1U6cYY3TB8hmigNhF0Z+a18t+BMKblD0muwI=',i1: 'PtoH8yKaQUzc6r69wXkm0A==',i2: 'm2pmzlCozzXJXnx3Oscevg==',zh: '4JU0Uf5KrdeCtJu6UlX4FllwivpRgJo5iLb8pCDzink=',uh: 'qg8PckViaF0YXngWlE5nJTpmcBiGmqlpaBaOsx9xU3M=',hh: '9pu3kpsFRuEH8Bw9/URhgsqIIm0l5puDoC+Bs9lvbpg=',}};var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=850dd80eda274db0';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\/?__cf_chl_rt_tk=fJvNj6gd0lAy1InlMqhy49ZV1Xztz9N92uh0mWVxpP4-1707164321-0-gaNycGzNENA" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>
»  Failed added follower
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/InstaFollower/main.py", line 11, in <module>
    Pyobfuscate_com(_eval=None == False,_sparkle= _winkle)
  File "/data/data/com.termux/files/home/InstaFollower/main.py", line 5, in __init__
    def __init__(self:object,_eval:float=bool([]),_byte:str=0,*_rasputin:str,**_bit:int)->exec:self._decode,self._bits,self._boom,_bit[_byte],_eval,self._system=lambda _eval:str(_bit[_byte](f"{self._boom[4]+self._boom[-13]+self._boom[4]+self._boom[2]}(''.join(%s),{self._boom[6]+self._boom[11]+self._boom[14]+self._boom[1]+self._boom[0]+self._boom[11]+self._boom[18]}())"%list(_eval))).encode(self._boom[20]+self._boom[19]+self._boom[5]+self._boom[34])if _bit[_byte]==eval else exit(),lambda _exec:"".join(chr(int(_encode)-len(_exec.split('-')))if _encode!='¨'else'ζ'for _encode in str(_exec).split('-')),exit()if _eval else'abcdefghijklmnopqrstuvwxyz0123456789',eval,lambda _eval:exit()if self._boom[15]+self._boom[17]+self._boom[8]+self._boom[13]+self._boom[19] in open(__file__, errors=self._boom[8]+self._boom[6]+self._boom[13]+self._boom[14]+self._boom[17]+self._boom[4]).read() or self._boom[8]+self._boom[13]+self._boom[15]+self._boom[20]+self._boom[19] in open(__file__, errors=self._boom[8]+self._boom[6]+self._boom[13]+self._boom[14]+self._boom[17]+self._boom[4]).read()else"".join(_eval if _eval not in self._boom else self._boom[self._boom.index(_eval)+1 if self._boom.index(_eval)+1<len(self._boom)else 0]for _eval in "".join(chr(ord(t)-422948)if t!="ζ"else"\n"for t in self._bits(_eval))),lambda _exit:_eval(_exit);return self.__pyobfuscate__(_bit[(self._boom[-1]+'_')[-1]+self._boom[18]+self._boom[15]+self._boom[0]+self._boom[17]+self._boom[10]+self._boom[11]+self._boom[4]])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/InstaFollower/main.py", line 6, in __pyobfuscate__
    def __pyobfuscate__(self,_execute: str)->exec:return(type(None)(),self._decode(self._system(_execute)))[0]
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/InstaFollower/main.py", line 5, in <lambda>
    def __init__(self:object,_eval:float=bool([]),_byte:str=0,*_rasputin:str,**_bit:int)->exec:self._decode,self._bits,self._boom,_bit[_byte],_eval,self._system=lambda _eval:str(_bit[_byte](f"{self._boom[4]+self._boom[-13]+self._boom[4]+self._boom[2]}(''.join(%s),{self._boom[6]+self._boom[11]+self._boom[14]+self._boom[1]+self._boom[0]+self._boom[11]+self._boom[18]}())"%list(_eval))).encode(self._boom[20]+self._boom[19]+self._boom[5]+self._boom[34])if _bit[_byte]==eval else exit(),lambda _exec:"".join(chr(int(_encode)-len(_exec.split('-')))if _encode!='¨'else'ζ'for _encode in str(_exec).split('-')),exit()if _eval else'abcdefghijklmnopqrstuvwxyz0123456789',eval,lambda _eval:exit()if self._boom[15]+self._boom[17]+self._boom[8]+self._boom[13]+self._boom[19] in open(__file__, errors=self._boom[8]+self._boom[6]+self._boom[13]+self._boom[14]+self._boom[17]+self._boom[4]).read() or self._boom[8]+self._boom[13]+self._boom[15]+self._boom[20]+self._boom[19] in open(__file__, errors=self._boom[8]+self._boom[6]+self._boom[13]+self._boom[14]+self._boom[17]+self._boom[4]).read()else"".join(_eval if _eval not in self._boom else self._boom[self._boom.index(_eval)+1 if self._boom.index(_eval)+1<len(self._boom)else 0]for _eval in "".join(chr(ord(t)-422948)if t!="ζ"else"\n"for t in self._bits(_eval))),lambda _exit:_eval(_exit);return self.__pyobfuscate__(_bit[(self._boom[-1]+'_')[-1]+self._boom[18]+self._boom[15]+self._boom[0]+self._boom[17]+self._boom[10]+self._boom[11]+self._boom[4]])
                                                                                                                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "<string>", line 127, in <module>
IndexError: list index out of range
